### ISSUE TITLE
parts

### ISSUE THREAD

**Issue by fi0** [haru-ake/lets-split-pcb-hs-cherry#1]
is there a parts list?

Should I use 1N4148W sod-123?

**Comment by haru-ake** [comment]
Hi @fi0 

Build log and parts list is [here](https://gist.github.com/haru-ake/80f2d0f08a26dfb094647d9ef05c46d1).
// Sorry. written by Japanese.

For PCB Rev 1.1.0, you can use either 1N4148W or 1N4148.
